-- 0019_episodic_distillations.sql
--
-- Apply by hand in the Supabase SQL editor against chat_db. Idempotent.
--
-- Phase 7 of docs/superpowers/plans/2026-08-20-p1-resolvable-context-modules.md.
--
-- Distilled historic understanding per grid / per organization, generated by a
-- nightly batch (anansi_app/scripts/episodic_scheduler.py, over
-- shared/episodic_memory.py) and read at render time by EpisodicProvider.
-- NOTE: from 0019 until 2026-08-25 nothing scheduled that batch and repo-root
-- scripts/ was in no deployed image, so this table stayed empty and the
-- episodic context module contributed nothing. Deliberately NOT conversation_summaries, which is per-session
-- and wired to progressive within-session summarization -- a different lifecycle.
--
-- edited_by set = an operator corrected this row by hand; the nightly job leaves
-- it alone thereafter.

BEGIN;

CREATE TABLE IF NOT EXISTS episodic_distillations (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    anchor_type    text NOT NULL,
    anchor_id      text NOT NULL,
    anchor_name    text,
    summary        text NOT NULL,
    message_count  integer NOT NULL DEFAULT 0,
    covers_from    timestamptz,
    covers_to      timestamptz,
    generated_at   timestamptz NOT NULL DEFAULT now(),
    edited_by      text,
    CONSTRAINT episodic_anchor_type_chk CHECK (anchor_type IN ('grid', 'organization')),
    CONSTRAINT episodic_anchor_unique UNIQUE (anchor_type, anchor_id)
);

CREATE INDEX IF NOT EXISTS episodic_distillations_anchor_idx
    ON episodic_distillations (anchor_type, anchor_id);

COMMIT;
