-- Grid Designs & BOMs — schema for the shared Supabase (anansi chat DB).
-- GENERATED by scripts/gen_schema.py — do not edit by hand.
-- Tables are prefixed gd_ and live in the public schema alongside anansi's.
-- Run in the Supabase SQL editor.
--
-- Note: AppSheet stored most values as free text; columns flagged numeric/
-- boolean in db/column_map.py are typed accordingly, the rest stay text.
-- FK relationships are indexed and documented but NOT hard-enforced in v1
-- (historical data has dangling refs).

-- ── Organizations (Admin) ────────────────────
CREATE TABLE IF NOT EXISTS gd_organizations (
    id                                 text PRIMARY KEY,
    name                               text,
    active                             boolean DEFAULT true,
    created_by                         text,
    created_at                         timestamptz DEFAULT now()
);

-- ── Users (Admin) ────────────────────
CREATE TABLE IF NOT EXISTS gd_users (
    id                                 text PRIMARY KEY,
    name                               text,
    organization                       text,
    email                              text,
    can                                text,
    active                             boolean DEFAULT true
);
CREATE INDEX IF NOT EXISTS gd_users_organization_idx ON gd_users (organization);  -- FK -> gd_organizations(id)

-- ── Grids (Sites) ────────────────────
CREATE TABLE IF NOT EXISTS gd_grids (
    id                                 text PRIMARY KEY,
    name                               text,
    community                          text,
    stage                              text,
    created_at                         timestamptz DEFAULT now(),
    active                             boolean DEFAULT true
);

-- ── Grid Coordinates (Sites) ────────────────────
CREATE TABLE IF NOT EXISTS gd_grid_coords (
    id                                 text PRIMARY KEY,
    grid                               text,
    coordinate                         text,
    active                             boolean DEFAULT true
);
CREATE INDEX IF NOT EXISTS gd_grid_coords_grid_idx ON gd_grid_coords (grid);  -- FK -> gd_grids(id)

-- ── Components (Catalogue) ────────────────────
CREATE TABLE IF NOT EXISTS gd_components (
    id                                 text PRIMARY KEY,
    name                               text,
    name_in_french                     text,
    counting_unit                      text,
    component_type                     text,
    source                             text,
    who_procures                       text,
    unit_cost_usd                      numeric,
    unit_cost_ngn                      numeric,
    spec1_name                         text,
    spec1_value                        text,
    spec1_unit                         text,
    spec2_name                         text,
    spec2_value                        text,
    spec2_unit                         text,
    spec3_name                         text,
    spec3_value                        text,
    spec3_unit                         text,
    contingency_pct                    numeric,
    created_at                         timestamptz DEFAULT now(),
    active                             boolean DEFAULT true,
    notes                              text,
    do_not_miss                        boolean,
    ddp_cost                           numeric,
    projected_cost                     numeric,
    cost_confidence                    text,
    num_purchases                      numeric,
    cost_projected_at                  timestamptz
);

-- ── Subassemblies (Catalogue) ────────────────────
CREATE TABLE IF NOT EXISTS gd_subassemblies (
    id                                 text PRIMARY KEY,
    main_component                     text,
    assembly_class                     text,
    assembly_type                      text,
    assembly_reference_image           text,
    description                        text,
    design_types                       text,
    components_active                  boolean,
    spec1_name                         text,
    spec1_value                        text,
    spec1_unit                         text,
    spec2_name                         text,
    spec2_value                        text,
    spec2_unit                         text,
    spec3_name                         text,
    spec3_value                        text,
    spec3_unit                         text,
    unit_rental_usd_per_month          numeric,
    created_at                         timestamptz DEFAULT now(),
    created_by                         text,
    updated_at                         timestamptz DEFAULT now(),
    updated_by                         text,
    active                             boolean DEFAULT true
);
CREATE INDEX IF NOT EXISTS gd_subassemblies_main_component_idx ON gd_subassemblies (main_component);  -- FK -> gd_components(id)

-- ── Subassembly Components (Catalogue) ────────────────────
CREATE TABLE IF NOT EXISTS gd_subassembly_components (
    id                                 text PRIMARY KEY,
    subassembly                        text,
    component_subassembly              text,
    component                          text,
    qty                                numeric,
    component_type                     text,
    unit                               text,
    spec1_name                         text,
    spec1_value                        text,
    spec1_unit                         text,
    created_at                         timestamptz DEFAULT now(),
    created_by                         text,
    updated_at                         timestamptz DEFAULT now(),
    updated_by                         text,
    active                             boolean DEFAULT true
);
CREATE INDEX IF NOT EXISTS gd_subassembly_components_subassembly_idx ON gd_subassembly_components (subassembly);  -- FK -> gd_subassemblies(id)
CREATE INDEX IF NOT EXISTS gd_subassembly_components_component_subassembly_idx ON gd_subassembly_components (component_subassembly);  -- FK -> gd_subassemblies(id)
CREATE INDEX IF NOT EXISTS gd_subassembly_components_component_idx ON gd_subassembly_components (component);  -- FK -> gd_components(id)

-- ── Design Rules (Catalogue) ────────────────────
CREATE TABLE IF NOT EXISTS gd_design_rules (
    id                                 text PRIMARY KEY,
    name                               text,
    description                        text,
    value                              text,
    created_at                         timestamptz DEFAULT now(),
    created_by                         text,
    implemented                        boolean,
    active                             boolean DEFAULT true
);

-- ── Designs (Engineering) ────────────────────
CREATE TABLE IF NOT EXISTS gd_designs (
    id                                 text PRIMARY KEY,
    grid                               text,
    name                               text,
    inverter_type                      text,
    battery_type                       text,
    mppt_type                          text,
    pv_type                            text,
    pv_inverter_type                   text,
    max_connections                    numeric,
    initial_residential_connections    numeric,
    initial_business_connections       numeric,
    initial_3_phase_connections        numeric,
    average_service_drop_length_m      numeric,
    number_of_poc_teams_to_install_meters numeric,
    anchor_load_kw                     numeric,
    force_3_phase                      boolean,
    wp_per_conn_override               numeric,
    constrain_design_to_known_regulation text,
    pue_hours_per_day                  numeric,
    daily_generation_potential_kwh_kwp numeric,
    phases                             text,
    target_kwp                         numeric,
    target_kwh                         numeric,
    target_tariff_usd                  numeric,
    auto_design                        boolean,
    recalculate_bom_on_design_change   boolean,
    max_distance_to_center_of_consumption numeric,
    pv_area_sqm                        numeric,
    avg_distance_to_pv_combiner        numeric,
    distance_to_feeder_pillar          numeric,
    spd_type                           text,
    usd_to_ngn                         numeric,
    xrate_updated_at                   timestamptz,
    bom_generated_at                   timestamptz,
    created_at                         timestamptz DEFAULT now(),
    created_by                         text,
    design_checks                      text,
    kwp                                numeric,
    kva                                numeric,
    kwh                                numeric,
    bom_cost_estimate                  numeric,
    works_cost_estimate                numeric,
    monthly_rental_estimate            numeric,
    monthly_saleable_kwh_at_expected_cuf numeric,
    monthly_revenue_at_expected_cuf_and_tariff numeric,
    active                             boolean DEFAULT true,
    artifacts                          jsonb DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS gd_designs_grid_idx ON gd_designs (grid);  -- FK -> gd_grids(id)

-- ── Design Subassemblies (Engineering) ────────────────────
CREATE TABLE IF NOT EXISTS gd_design_subassemblies (
    id                                 text PRIMARY KEY,
    design                             text,
    subassembly                        text,
    qty                                numeric,
    subassembly_image                  text,
    named                              text,
    class                              text,
    spec1_name                         text,
    spec1_value                        text,
    spec1_unit                         text,
    spec2_name                         text,
    spec2_value                        text,
    spec2_unit                         text,
    spec3_name                         text,
    spec3_value                        text,
    spec3_unit                         text,
    kwp                                numeric,
    kwh                                numeric,
    kva                                numeric,
    active                             boolean DEFAULT true,
    comment                            text,
    manually_edited                    boolean DEFAULT false
);
CREATE INDEX IF NOT EXISTS gd_design_subassemblies_design_idx ON gd_design_subassemblies (design);  -- FK -> gd_designs(id)
CREATE INDEX IF NOT EXISTS gd_design_subassemblies_subassembly_idx ON gd_design_subassemblies (subassembly);  -- FK -> gd_subassemblies(id)

-- ── BOM Items (Engineering) ────────────────────
CREATE TABLE IF NOT EXISTS gd_bom_items (
    id                                 text PRIMARY KEY,
    item                               text,
    qty                                numeric,
    qty_with_contingency               numeric,
    design                             text,
    job                                text,
    subassembly                        text,
    design_types                       text,
    unit_cost_ngn                      numeric,
    total_cost_ngn                     numeric,
    monthly_rental_usd                 numeric,
    source                             text,
    who_procures                       text,
    verified_in_shipment               boolean,
    engg_comment                       text,
    received_count                     numeric,
    returned_count                     numeric,
    technician_comment                 text,
    active                             boolean DEFAULT true
);
CREATE INDEX IF NOT EXISTS gd_bom_items_item_idx ON gd_bom_items (item);  -- FK -> gd_components(id)
CREATE INDEX IF NOT EXISTS gd_bom_items_design_idx ON gd_bom_items (design);  -- FK -> gd_designs(id)
CREATE INDEX IF NOT EXISTS gd_bom_items_job_idx ON gd_bom_items (job);  -- FK -> gd_jobs(id)
CREATE INDEX IF NOT EXISTS gd_bom_items_subassembly_idx ON gd_bom_items (subassembly);  -- FK -> gd_subassemblies(id)

-- ── Procedures (Field Ops) ────────────────────
CREATE TABLE IF NOT EXISTS gd_procedures (
    id                                 text PRIMARY KEY,
    code                               text,
    name                               text,
    qty                                numeric,
    comments                           text,
    active                             boolean DEFAULT true
);

-- ── Procedure Steps (Field Ops) ────────────────────
CREATE TABLE IF NOT EXISTS gd_procedure_steps (
    id                                 text PRIMARY KEY,
    name                               text,
    type                               text,
    outcomes                           text,
    procedure                          text,
    detail                             text,
    image                              text,
    requires_proof                     boolean,
    step_order                         numeric,
    conditional_on                     text,
    go_options                         text,
    active                             boolean DEFAULT true,
    created_by                         text,
    created_at                         timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS gd_procedure_steps_procedure_idx ON gd_procedure_steps (procedure);  -- FK -> gd_procedures(id)
CREATE INDEX IF NOT EXISTS gd_procedure_steps_conditional_on_idx ON gd_procedure_steps (conditional_on);  -- FK -> gd_procedure_steps(id)

-- ── Jobs (Field Ops) ────────────────────
CREATE TABLE IF NOT EXISTS gd_jobs (
    id                                 text PRIMARY KEY,
    type                               text,
    grid                               text,
    jira_reference                     text,
    organization                       text,
    technician                         text,
    start_date                         text,
    expected_days_to_complete          numeric,
    cost_to_developer                  numeric,
    cost_to_nxt                        numeric,
    status                             text,
    created_at                         timestamptz DEFAULT now(),
    created_by                         text,
    active                             boolean DEFAULT true
);
CREATE INDEX IF NOT EXISTS gd_jobs_grid_idx ON gd_jobs (grid);  -- FK -> gd_grids(id)
CREATE INDEX IF NOT EXISTS gd_jobs_organization_idx ON gd_jobs (organization);  -- FK -> gd_organizations(id)
CREATE INDEX IF NOT EXISTS gd_jobs_technician_idx ON gd_jobs (technician);  -- FK -> gd_users(id)

-- ── Job Procedures (Field Ops) ────────────────────
CREATE TABLE IF NOT EXISTS gd_job_procedures (
    id                                 text PRIMARY KEY,
    job                                text,
    procedure                          text,
    qty                                numeric,
    sequence_in_job                    numeric,
    status                             text,
    active                             boolean DEFAULT true,
    comment                            text
);
CREATE INDEX IF NOT EXISTS gd_job_procedures_job_idx ON gd_job_procedures (job);  -- FK -> gd_jobs(id)
CREATE INDEX IF NOT EXISTS gd_job_procedures_procedure_idx ON gd_job_procedures (procedure);  -- FK -> gd_procedures(id)

-- ── Job Steps (Field Ops) ────────────────────
CREATE TABLE IF NOT EXISTS gd_job_steps (
    id                                 text PRIMARY KEY,
    name                               text,
    step_reference                     text,
    job                                text,
    job_procedure                      text,
    sequence                           numeric,
    conditional_on                     text,
    go_conditions                      text,
    proof                              text,
    status                             text,
    comment                            text,
    approved                           boolean,
    active                             boolean DEFAULT true,
    created_by                         text,
    updated_by                         text,
    created_at                         timestamptz DEFAULT now(),
    updated_at                         timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS gd_job_steps_job_idx ON gd_job_steps (job);  -- FK -> gd_jobs(id)
CREATE INDEX IF NOT EXISTS gd_job_steps_job_procedure_idx ON gd_job_steps (job_procedure);  -- FK -> gd_job_procedures(id)
CREATE INDEX IF NOT EXISTS gd_job_steps_step_reference_idx ON gd_job_steps (step_reference);  -- FK -> gd_procedure_steps(id)

-- ── Job Subassemblies (Field Ops) ────────────────────
CREATE TABLE IF NOT EXISTS gd_job_subassemblies (
    id                                 text PRIMARY KEY,
    job                                text,
    subassembly                        text,
    qty                                numeric,
    active                             boolean DEFAULT true,
    comment                            text
);
CREATE INDEX IF NOT EXISTS gd_job_subassemblies_job_idx ON gd_job_subassemblies (job);  -- FK -> gd_jobs(id)
CREATE INDEX IF NOT EXISTS gd_job_subassemblies_subassembly_idx ON gd_job_subassemblies (subassembly);  -- FK -> gd_subassemblies(id)

-- ── Purchases (BoS) (Procurement) ────────────────────
CREATE TABLE IF NOT EXISTS gd_purchases (
    id                                 text PRIMARY KEY,
    date                               timestamptz,
    item_description                   text,
    currency                           text,
    qty                                numeric,
    landed_unit_cost_usd               numeric,
    total_cost                         numeric,
    active                             boolean DEFAULT true
);

-- ── Unit Rental Prices (Catalogue) ────────────────────
CREATE TABLE IF NOT EXISTS gd_unit_rental_prices (
    id                                 text PRIMARY KEY,
    item                               text,
    engineering_item_name              text,
    unit_monthly_rental                numeric,
    active                             boolean DEFAULT true
);

-- ── Wp per Conn Lookup (Catalogue) ────────────────────
CREATE TABLE IF NOT EXISTS gd_wp_per_conn_lookup (
    id                                 text PRIMARY KEY,
    nonresidential_threshold           numeric,
    wp_per_conn                        numeric,
    kwh_per_kwp                        numeric,
    active                             boolean DEFAULT true
);
