"""PDF audit certificate and signature stamping helpers.

Extracted from router.py (Single Responsibility: PDF rendering has no HTTP concepts).
router.py imports these via: from orchestrator.mini_app.audit import ...
"""

# Colour palette for the audit certificate page
_AUDIT_DARK = (0.10, 0.10, 0.10)
_AUDIT_BLUE = (0.05, 0.35, 0.65)
_AUDIT_GREY = (0.45, 0.45, 0.45)
_AUDIT_LIGHT = (0.92, 0.94, 0.97)


def _generate_audit_page(audit_data: dict) -> bytes:
    """Generate a single-page A4 PDF audit trail certificate.

    Uses pymupdf (fitz) which is already a project dependency for PDF stamping.
    The page is appended to the signed document so the full audit record travels
    with the file, matching the HelloSign / Dropbox Sign model.

    audit_data keys:
        document_name, packet_id, requester_name, requester_email,
        sent_at, viewed_at (optional), signer_name, signer_ip (optional),
        signed_at, original_sha256, signed_sha256
    """
    import fitz  # pymupdf — already used for PDF stamping

    doc = fitz.open()
    page = doc.new_page(width=595, height=842)  # A4 points

    # ── Header band ──────────────────────────────────────────────────────
    page.draw_rect(fitz.Rect(0, 0, 595, 80), color=_AUDIT_BLUE, fill=_AUDIT_BLUE)
    page.insert_text(
        (40, 38),
        "Digital Audit Trail",
        fontsize=20,
        fontname="helv",
        color=(1, 1, 1),
    )
    page.insert_text(
        (40, 60),
        "Signing Certificate  ·  Generated by Anansi",
        fontsize=9,
        fontname="helv",
        color=(0.80, 0.88, 1.0),
    )

    # ── Document info ────────────────────────────────────────────────────
    y: float = 100
    page.insert_text((40, y), "Document", fontsize=8, fontname="helv", color=_AUDIT_GREY)
    page.insert_text(
        (40, y + 13),
        audit_data.get("document_name", "—"),
        fontsize=11,
        fontname="helv",
        color=_AUDIT_DARK,
    )
    page.insert_text((320, y), "Audit ID", fontsize=8, fontname="helv", color=_AUDIT_GREY)
    page.insert_text(
        (320, y + 13),
        audit_data.get("packet_id", "—")[:36],
        fontsize=9,
        fontname="cour",
        color=_AUDIT_DARK,
    )

    # Divider
    y = 140.0
    page.draw_line((40, y), (555, y), color=(0.80, 0.80, 0.80), width=0.5)

    # ── Event timeline ───────────────────────────────────────────────────
    y = 158.0
    page.insert_text((40, y), "TIMELINE OF EVENTS", fontsize=8, fontname="helv", color=_AUDIT_BLUE)
    y += 18

    events = [
        (
            "Document Sent",
            audit_data.get("sent_at", "—"),
            "  ·  ".join(
                filter(
                    None, [audit_data.get("requester_name", "—"), audit_data.get("requester_email")]
                )
            ),
            None,
        ),
        (
            "Document Viewed",
            audit_data.get("viewed_at") or "—",
            audit_data.get("signer_name", "—"),
            audit_data.get("signer_ip"),
        ),
        (
            "Document Signed",
            audit_data.get("signed_at", "—"),
            audit_data.get("signer_name", "—"),
            audit_data.get("signer_ip"),
        ),
    ]
    for label, ts, who, ip in events:
        # Draw background stripe first so text is rendered on top (fitz painter's model)
        page.draw_rect(fitz.Rect(40, y - 8, 555, y + 34), color=_AUDIT_LIGHT, fill=_AUDIT_LIGHT)
        page.draw_circle(fitz.Point(48, y - 4), 4, color=_AUDIT_BLUE, fill=_AUDIT_BLUE)
        page.insert_text((62, y), label, fontsize=10, fontname="helv", color=_AUDIT_DARK)
        page.insert_text((62, y + 14), ts or "—", fontsize=8, fontname="cour", color=_AUDIT_GREY)
        detail = f"{who}  ·  IP: {ip}" if ip else who
        page.insert_text((62, y + 26), detail, fontsize=8, fontname="helv", color=_AUDIT_GREY)
        y += 56  # advance past stripe + gap

    # ── Document integrity ───────────────────────────────────────────────
    y += 10
    page.draw_line((40, y), (555, y), color=(0.80, 0.80, 0.80), width=0.5)
    y += 16
    page.insert_text((40, y), "DOCUMENT INTEGRITY", fontsize=8, fontname="helv", color=_AUDIT_BLUE)
    y += 16
    page.insert_text((40, y), "Original SHA-256", fontsize=8, fontname="helv", color=_AUDIT_GREY)
    page.insert_text(
        (40, y + 12),
        audit_data.get("original_sha256", "—"),
        fontsize=8,
        fontname="cour",
        color=_AUDIT_DARK,
    )
    y += 30
    page.insert_text(
        (40, y),
        "Signed SHA-256  (covers stamped document, excludes this page)",
        fontsize=8,
        fontname="helv",
        color=_AUDIT_GREY,
    )
    page.insert_text(
        (40, y + 12),
        audit_data.get("signed_sha256", "—"),
        fontsize=8,
        fontname="cour",
        color=_AUDIT_DARK,
    )

    # ── Footer ───────────────────────────────────────────────────────────
    page.draw_rect(fitz.Rect(0, 800, 595, 842), color=_AUDIT_LIGHT, fill=_AUDIT_LIGHT)
    page.insert_text(
        (40, 820),
        "Signer identity verified via Telegram HMAC (cryptographically bound to phone number). "
        "This record is tamper-evident: any modification to the signed document changes its SHA-256.",
        fontsize=7,
        fontname="helv",
        color=_AUDIT_GREY,
    )

    audit_bytes: bytes = doc.tobytes()
    doc.close()
    return audit_bytes


def _merge_audit_page_sync(signed_bytes: bytes, audit_page_bytes: bytes) -> bytes:
    """Append audit page to signed PDF and return merged bytes.

    Synchronous — call via asyncio.to_thread to avoid blocking the event loop
    during fitz.open / insert_pdf / tobytes operations.
    """
    import fitz  # pymupdf

    signed_doc = fitz.open(stream=signed_bytes, filetype="pdf")
    audit_doc = fitz.open(stream=audit_page_bytes, filetype="pdf")
    signed_doc.insert_pdf(audit_doc)
    merged: bytes = signed_doc.tobytes()
    signed_doc.close()
    audit_doc.close()
    return merged


def _stamp_pdf_sync(
    original_bytes: bytes,
    page: int,
    x: float,
    y: float,
    sig_bytes: bytes,
    w_frac: float = 0.25,
    h_frac: float = 0.08,
) -> tuple[bytes, float, float, float, float]:
    """Stamp signature onto PDF page and return (signed_bytes, x1, y1, x2, y2).

    The signed page is rasterized so the signature is flattened into the page
    content and cannot be selected or extracted as an object.
    Synchronous — call via asyncio.to_thread to avoid blocking the event loop.
    """
    import fitz  # pymupdf

    doc = fitz.open(stream=original_bytes, filetype="pdf")
    if page >= len(doc):
        raise ValueError(f"Page {page} does not exist in this document ({len(doc)} pages)")
    pg = doc[page]
    x1 = x * pg.rect.width
    y1 = y * pg.rect.height
    x2 = x1 + w_frac * pg.rect.width
    y2 = y1 + h_frac * pg.rect.height
    pg.insert_image(fitz.Rect(x1, y1, x2, y2), stream=sig_bytes, keep_proportion=True)

    # Flatten the signed page by rasterizing it — signature becomes unselectable content
    pix = pg.get_pixmap(dpi=120, colorspace=fitz.csRGB)

    # Build output: rasterized signed page + all other pages copied as-is
    out_doc = fitz.open()
    for i in range(len(doc)):
        src = doc[i]
        if i == page:
            flat_pg = out_doc.new_page(width=src.rect.width, height=src.rect.height)
            flat_pg.insert_image(flat_pg.rect, pixmap=pix)
            del pix  # release ~10 MB before tobytes() allocates output buffer
        else:
            out_doc.insert_pdf(doc, from_page=i, to_page=i)

    return out_doc.tobytes(), x1, y1, x2, y2
