"""Entity metadata layer.

Loads ``db/entities.json`` (generated by ``scripts/gen_schema.py``) and wraps each
table as an ``EntitySpec`` that the generic views render. This is the AppSheet-style
"declare once, render everywhere" core: ~17 tables share three renderers instead of
hand-coding 50+ views.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path

from shared.grid_design.db import Repository

ENTITIES_PATH = Path(__file__).resolve().parents[2] / "db" / "entities.json"

# Acronyms to preserve when prettifying column names into labels.
_ACRONYMS = {
    "id": "ID",
    "ngn": "NGN",
    "usd": "USD",
    "kwp": "kWp",
    "kwh": "kWh",
    "kva": "kVA",
    "kw": "kW",
    "pv": "PV",
    "ac": "AC",
    "dc": "DC",
    "spd": "SPD",
    "mppt": "MPPT",
    "bom": "BOM",
    "poc": "PoC",
    "cuf": "CUF",
    "pue": "PUE",
    "sqm": "sq.m",
    "pct": "%",
    "3": "3",
}

# Columns rendered as multi-line text areas.
_LONG_TEXT = {
    "description",
    "notes",
    "comment",
    "comments",
    "detail",
    "outcomes",
    "design_checks",
    "engg_comment",
    "technician_comment",
}

# Known enum options (others fall back to free text). Values must match what is
# stored in the DB — verified against live data 2026-06-27.
ENUMS: dict[tuple[str, str], list[str]] = {
    # ── Subassemblies ──────────────────────────────────────────────────────────
    ("subassemblies", "assembly_class"): [
        "Energy Cabin or Cabinet",
        "MPPT (+Panels)",
        "Hybrid ESS",
        "PV Inverter (+Panels)",
        "Inverter Charger",
        "Hybrid Inverter (MPPT and AC Charger + Inverter)",
        "Generator",
        "Battery",
        "Conductor",
        "Lightning Arresters",
        "Grounding",
        "AC Bus",
        "Metering",
        "DC Bus",
    ],
    # NB: "Maintainance" is the AppSheet/DB spelling — not a typo here.
    ("subassemblies", "assembly_type"): ["Build", "Upgrade", "Maintainance"],
    ("subassemblies", "design_types"): ["Victron", "Deye", "Victron and Deye"],
    # ── Designs ────────────────────────────────────────────────────────────────
    ("designs", "constrain_design_to_known_regulation"): ["None", "Nigeria - DARES"],
    ("designs", "phases"): ["1-phase", "3-phase"],
    ("designs", "spd_type"): [
        "Keep default T1+T2 Type SPD (Any lightning probability)",
        "Use T2 type as T1+T2 Type due to Low (<=16 strikes per sq km per yr) lightning probability",
    ],
    # ── Jobs & field ops ───────────────────────────────────────────────────────
    ("jobs", "type"): ["3P", "NXT"],
    ("jobs", "status"): ["🟡 Pending", "🚧 Site work ongoing", "🟢 Done", "⃠ Cancelled"],
    ("job_procedures", "status"): ["🟡 Pending", "🟢 Done Ok", "🔴 Failed", "⃠ Cancelled"],
    ("job_steps", "status"): [
        "🟡 Pending",
        "◐ Partly Done",
        "🟢 Done",
        "🔴 Failed",
        "⃠ Not Applicable",
    ],
    # ── Purchases ──────────────────────────────────────────────────────────────
    ("purchases", "currency"): ["USD", "NGN"],
}


def prettify(col: str) -> str:
    parts = col.split("_")
    return " ".join(_ACRONYMS.get(p, p.capitalize()) for p in parts)


def _widget(col: str, ctype: str, ref: str | None) -> str:
    if ref:
        return "ref"
    if "image" in col or col == "proof":
        return "image"
    if ctype == "numeric":
        return "number"
    if ctype == "boolean":
        return "bool"
    if ctype == "timestamptz":
        return "datetime"
    if col in _LONG_TEXT:
        return "textarea"
    return "text"


@dataclass
class ColumnSpec:
    name: str
    ctype: str
    ref: str | None
    label: str
    widget: str
    options: list[str] | None = None

    @property
    def editable(self) -> bool:
        return self.name not in ("id", "created_at", "updated_at", "created_by", "updated_by")


@dataclass
class EntitySpec:
    bare: str
    label: str
    icon: str
    group: str
    pk: str
    columns: list[ColumnSpec] = field(default_factory=list)

    def repo(self) -> Repository:
        return Repository(self.bare, pk=self.pk)

    def col(self, name: str) -> ColumnSpec | None:
        return next((c for c in self.columns if c.name == name), None)

    @property
    def label_column(self) -> str:
        """Best human-friendly column to represent a row (for ref dropdowns)."""
        for cand in ("name", "description", "item_description", "item", "code", "title"):
            if self.col(cand):
                return cand
        return "id"

    def list_columns(self) -> list[ColumnSpec]:
        """Curated, compact set for the table/list view (detail shows all)."""
        picked: list[ColumnSpec] = []
        names: set[str] = set()

        def add(c: ColumnSpec | None):
            if c and c.name not in names:
                picked.append(c)
                names.add(c.name)

        # Only lead with label_column if it's a real label, not the id fallback.
        label = self.label_column
        if label != "id":
            add(self.col(label))
        for c in self.columns:  # references
            if c.ref:
                add(c)
        for key in (
            "date",
            "code",
            "type",
            "component_type",
            "assembly_type",
            "assembly_class",
            "counting_unit",
            "status",
            "stage",
            "currency",
            "qty",
            "value",
            "total_cost",
            "landed_unit_cost_usd",
            "unit_cost_usd",
            "ddp_cost",
            "projected_cost",
            "source",
            "who_procures",
            "num_purchases",
            "cost_confidence",
            "engineering_item_name",
            "unit_monthly_rental",
            "nonresidential_threshold",
            "wp_per_conn",
            "kwh_per_kwp",
        ):
            add(self.col(key))
        if len(picked) < 2 and self.col("id"):
            add(self.col("id"))
        return picked[:8]


@lru_cache(maxsize=1)
def _load() -> dict[str, EntitySpec]:
    data = json.loads(ENTITIES_PATH.read_text())
    out: dict[str, EntitySpec] = {}
    for t in data["tables"]:
        cols = []
        for c in t["columns"]:
            opts = ENUMS.get((t["bare"], c["name"]))
            cols.append(
                ColumnSpec(
                    name=c["name"],
                    ctype=c["type"],
                    ref=c.get("ref"),
                    label=prettify(c["name"]),
                    widget="enum" if opts else _widget(c["name"], c["type"], c.get("ref")),
                    options=opts,
                )
            )
        out[t["bare"]] = EntitySpec(
            bare=t["bare"],
            label=t["label"],
            icon=t["icon"],
            group=t["group"],
            pk=t["pk"],
            columns=cols,
        )
    return out


def get_entity(bare: str) -> EntitySpec | None:
    return _load().get(bare)


def all_entities() -> list[EntitySpec]:
    return list(_load().values())


def grouped_entities() -> dict[str, list[EntitySpec]]:
    groups: dict[str, list[EntitySpec]] = {}
    for e in all_entities():
        groups.setdefault(e.group, []).append(e)
    return groups


def reverse_relations(spec: EntitySpec) -> list[tuple[EntitySpec, ColumnSpec]]:
    """Return (child_spec, fk_col) for every FK in any entity that points at spec."""
    results = []
    for child in all_entities():
        for col in child.columns:
            if col.ref == spec.bare:
                results.append((child, col))
    return results
