"""
Response Verification Service (LLM-as-Judge)

Verifies responses before sending them using a separate LLM call.
This service implements quality control for both customer and staff mode responses.

The verification flow:
1. Original response generated by main conversation
2. Verification service checks response against criteria (from Google Doc)
3. If passed: response sent as-is
4. If failed: regenerate once with feedback, then escalate if still fails
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from shared.llm import GeminiGateway, GenerationOptions, LLMMessage
from shared.utils.langfuse_utils import langfuse_observe, score_trace
from shared.utils.logging import get_logger

LOGGER = get_logger(__name__)


@dataclass
class VerificationResult:
    """Result of response verification."""

    passed: bool
    feedback: str = ""
    categories: List[str] = field(default_factory=list)
    raw_response: Optional[str] = None

    def __bool__(self) -> bool:
        """Allow using result directly in conditionals."""
        return self.passed


class ResponseVerificationService:
    """
    Verifies response quality using LLM-as-judge pattern.

    Uses a lightweight model to evaluate responses against verification criteria
    before they are sent to customers.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: Optional[str] = None,
        gateway: Optional[GeminiGateway] = None,
    ):
        """
        Initialize verification service.

        Args:
            api_key: Google API key (defaults to GOOGLE_API_KEY env var)
            model: Gemini model to use (defaults to VERIFICATION_MODEL env var)
        """
        self._api_key = api_key or os.getenv("GOOGLE_API_KEY", "")
        self._model = model or os.getenv("VERIFICATION_MODEL", "gemini-2.5-flash-lite")
        self._gateway = gateway or GeminiGateway(
            api_key=self._api_key,
            default_model=self._model,
        )

    async def verify_response(
        self,
        original_message: str,
        response_text: str,
        verification_instructions: str,
        conversation_context: Optional[str] = None,
        available_tools: Optional[List[Dict[str, Any]]] = None,
        mode: str = "reply",
    ) -> VerificationResult:
        """
        Verify if a response meets quality standards.

        Args:
            original_message: The user's original message/question
            response_text: The response text to verify
            verification_instructions: Criteria from Google Doc
            conversation_context: Optional additional context from conversation
            available_tools: Optional list of tools available to the generating LLM
                (in Gemini format with functionDeclarations wrapper)
            mode: Verification mode. "reply" (default) verifies a response to a
                specific customer question. "broadcast" verifies a one-way
                announcement sent to many recipients — in this mode the judge does
                NOT expect the text to address a specific question, and Q&A-only
                failure categories (completeness/tool_awareness) are dropped.

        Returns:
            VerificationResult with passed status, feedback if failed, and categories
        """
        if not self._api_key:
            LOGGER.error("GOOGLE_API_KEY not set - cannot verify response")
            # Fail open: allow response through if verification unavailable
            return VerificationResult(
                passed=True,
                feedback="Verification skipped: API key not configured",
            )

        if not verification_instructions:
            LOGGER.warning("No verification instructions provided - skipping verification")
            return VerificationResult(
                passed=True,
                feedback="Verification skipped: no instructions configured",
            )

        # Prepend current date to system_instruction so the verifier model (which has a
        # training cutoff) does not incorrectly flag valid recent dates as future dates.
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        dated_instructions = f"TODAY'S DATE AND TIME: {today}\n\n{verification_instructions}"

        # Build verification prompt
        verification_prompt = self._build_verification_prompt(
            original_message=original_message,
            response_text=response_text,
            conversation_context=conversation_context,
            available_tools=available_tools,
            mode=mode,
        )

        try:
            # Call Gemini with verification model
            result = await self._call_gemini(
                system_instruction=dated_instructions,
                user_message=verification_prompt,
            )

            # Parse the response
            verification_result = self._parse_verification_response(result)

            # Log verification pass/fail as a Langfuse score
            score_trace(
                name="verification",
                value=1.0 if verification_result.passed else 0.0,
                comment=(
                    str(verification_result.categories) if not verification_result.passed else None
                ),
            )

            return verification_result

        except Exception as e:
            LOGGER.exception(f"Verification failed with error: {e}")
            # Fail open: allow response through if verification errors
            return VerificationResult(
                passed=True,
                feedback=f"Verification error: {str(e)}",
            )

    def _build_verification_prompt(
        self,
        original_message: str,
        response_text: str,
        conversation_context: Optional[str] = None,
        available_tools: Optional[List[Dict[str, Any]]] = None,
        mode: str = "reply",
    ) -> str:
        """Build the prompt for verification.

        The ``mode`` argument tailors the framing. For "broadcast" the text is a
        one-way announcement, so the judge is told not to expect it to answer a
        specific question and the Q&A-only categories are removed.
        """
        parts = []

        if conversation_context:
            parts.append(f"CONVERSATION CONTEXT:\n{conversation_context}\n")

        if mode == "broadcast":
            parts.append(
                "MESSAGE TYPE: One-way broadcast announcement.\n"
                "This message is proactively sent by staff to many customers at once. "
                "It is NOT a reply to a customer question, so do NOT fail it for not "
                "addressing a specific question, concern, or conversation. It may ask "
                "recipients to take an action (e.g. confirm something or send a photo) — "
                "that is a valid instruction, not an unclear request. Judge it only on "
                "the criteria in your instructions (tone, professionalism, safety, "
                "clarity, accuracy, no sensitive/internal information).\n"
                "Approved placeholder tags have ALREADY been substituted with the "
                "recipient's real values: organization, community, and grid names "
                "appearing in the text are real data, NOT placeholder tags. Only a "
                "literal angle-bracket token still present in the text (e.g. <some_tag>) "
                "counts as an unrecognized placeholder tag.\n"
            )
            parts.append(f"BROADCAST MESSAGE TO VERIFY:\n{response_text}\n")
            categories_block = """
Only include categories that actually failed. Common categories:
- "tone": Message tone is inappropriate
- "accuracy": Information may be incorrect
- "safety": Contains potentially harmful content or could cause undue alarm
- "clarity": Message is confusing or unclear
- "professionalism": Language is unprofessional
- "sensitive_info": Exposes internal information not meant for customers
"""
        else:
            # Include tool descriptions so verifier knows what the LLM could do
            if available_tools:
                tools_summary = self._format_tools_summary(available_tools)
                if tools_summary:
                    parts.append(
                        f"TOOLS AVAILABLE TO THE GENERATING LLM:\n"
                        f"(The LLM that generated the response had access to these tools. "
                        f"Consider this when evaluating whether the response appropriately used "
                        f"or referenced available capabilities.)\n\n{tools_summary}\n"
                    )

            parts.append(f"ORIGINAL USER MESSAGE:\n{original_message}\n")
            parts.append(f"RESPONSE TO VERIFY:\n{response_text}\n")
            categories_block = """
Only include categories that actually failed. Common categories:
- "tone": Response tone is inappropriate
- "accuracy": Information may be incorrect
- "completeness": Response doesn't fully address the question
- "safety": Contains potentially harmful content
- "clarity": Response is confusing or unclear
- "professionalism": Language is unprofessional
- "tool_awareness": Response claims inability to do something tools could accomplish
"""

        parts.append(
            """
Evaluate the response against the verification criteria provided in your instructions.

Respond with a JSON object (and nothing else):
{
  "passed": true or false,
  "feedback": "If failed, explain what needs to be fixed. If passed, leave empty.",
  "categories": ["list", "of", "failed", "criteria"]
}
"""
            + categories_block
        )

        return "\n".join(parts)

    def _format_tools_summary(
        self,
        available_tools: List[Dict[str, Any]],
    ) -> str:
        """
        Format available tools into a readable summary for verification.

        Args:
            available_tools: Tools in Gemini format (may have functionDeclarations wrapper)

        Returns:
            Formatted string with tool names and descriptions
        """
        tool_lines = []

        # Handle Gemini format: [{"functionDeclarations": [...]}]
        tools_list = []
        for item in available_tools:
            if isinstance(item, dict):
                if "functionDeclarations" in item:
                    tools_list.extend(item["functionDeclarations"])
                elif "name" in item:
                    # Direct tool definition
                    tools_list.append(item)

        for tool in tools_list:
            name = tool.get("name", "unknown")
            description = tool.get("description", "No description")
            # Truncate long descriptions
            if len(description) > 200:
                description = description[:197] + "..."
            tool_lines.append(f"- {name}: {description}")

        return "\n".join(tool_lines)

    @langfuse_observe(as_type="generation", name="verification-gemini")
    async def _call_gemini(
        self,
        system_instruction: str,
        user_message: str,
    ) -> str:
        """Make a Gemini API call for verification."""
        LOGGER.debug(f"Verification model: {self._model}")

        result = await self._gateway.generate(
            [
                LLMMessage(role="system", text=system_instruction),
                LLMMessage(role="user", text=user_message),
            ],
            GenerationOptions(
                model=self._model,
                temperature=0.1,
                max_output_tokens=int(os.getenv("GEMINI_LITE_MAX_OUTPUT_TOKENS", "1024")),
                response_format="json",
            ),
        )
        return result.text

    def _parse_verification_response(self, response_text: str) -> VerificationResult:
        """Parse the JSON verification response from Gemini."""
        if not response_text:
            LOGGER.warning("Empty verification response - treating as passed")
            return VerificationResult(
                passed=True,
                feedback="Verification returned empty response",
                raw_response=response_text,
            )

        # Try to extract JSON from the response
        # Sometimes models wrap JSON in markdown code blocks
        json_text = response_text.strip()
        if json_text.startswith("```"):
            # Remove markdown code block
            lines = json_text.split("\n")
            json_lines = []
            in_block = False
            for line in lines:
                if line.startswith("```"):
                    in_block = not in_block
                    continue
                if in_block or not line.startswith("```"):
                    json_lines.append(line)
            json_text = "\n".join(json_lines).strip()

        try:
            data = json.loads(json_text)

            passed = data.get("passed", True)
            feedback = data.get("feedback", "")
            categories = data.get("categories", [])

            # Ensure categories is a list
            if isinstance(categories, str):
                categories = [categories]

            LOGGER.info(
                f"Verification result: passed={passed}, "
                f"categories={categories}, "
                f"feedback_length={len(feedback)}"
            )

            return VerificationResult(
                passed=bool(passed),
                feedback=str(feedback),
                categories=list(categories),
                raw_response=response_text,
            )

        except json.JSONDecodeError as e:
            LOGGER.warning(
                f"Failed to parse verification JSON: {e}. Response: {response_text[:200]}..."
            )
            # If we can't parse, fail open
            return VerificationResult(
                passed=True,
                feedback=f"Could not parse verification response: {e}",
                raw_response=response_text,
            )

    async def sanitize_technical_response(
        self,
        response_text: str,
        context: str = "expert workflow",
    ) -> str:
        """
        Use LLM-as-judge to detect and rewrite responses with technical details.

        Checks for internal implementation details like step names, error codes,
        file paths, protection markers, and technical jargon that users shouldn't see.
        If detected, rewrites the response in user-friendly language.

        Args:
            response_text: The response text to check and potentially rewrite
            context: Brief description of what operation was being performed

        Returns:
            Original response if clean, or rewritten user-friendly version
        """
        if not response_text or not self._api_key:
            return response_text

        # Skip very short responses
        if len(response_text) < 20:
            return response_text

        sanitization_prompt = f"""Analyze this response that will be sent to a user. Check if it contains any internal technical details that should not be exposed:

RESPONSE TO CHECK:
{response_text}

CONTEXT: This response is from a {context}.

Check for these issues:
1. Internal step/function names (e.g., "step copy_lpp_template", "generate_distribution_map")
2. Protection markers (e.g., "__PROTECTED_CMD_", "⟦CMD")
3. File paths (e.g., "/app/orchestrator/...")
4. Python/code error traces or stack traces
5. Internal field names with underscores (e.g., "packet_state", "site_id")
6. Technical jargon the user wouldn't understand
7. Raw error codes or internal status values

Respond with JSON only:
{{
  "has_technical_details": true or false,
  "issues_found": ["list of specific issues found"],
  "rewritten_response": "If has_technical_details is true, provide a user-friendly version that conveys the same information without technical details. If false, leave empty."
}}

Guidelines for rewriting:
- Keep the same meaning and tone
- Replace technical terms with plain language
- If there was an error, explain what the user should do
- Be helpful and friendly
- Don't mention internal systems or step names"""

        try:
            result = await self._call_gemini(
                system_instruction="You are a response quality checker. Detect technical implementation details in user-facing messages and rewrite them to be user-friendly.",
                user_message=sanitization_prompt,
            )

            # Parse the response
            json_text = result.strip()
            if json_text.startswith("```"):
                lines = json_text.split("\n")
                json_lines = []
                in_block = False
                for line in lines:
                    if line.startswith("```"):
                        in_block = not in_block
                        continue
                    if in_block or not line.startswith("```"):
                        json_lines.append(line)
                json_text = "\n".join(json_lines).strip()

            data = json.loads(json_text)

            if data.get("has_technical_details") and data.get("rewritten_response"):
                LOGGER.info(f"Sanitized technical response. Issues: {data.get('issues_found', [])}")
                return str(data["rewritten_response"])

            return response_text

        except Exception as e:
            LOGGER.warning(f"Technical sanitization check failed: {e}")
            # Fail open - return original
            return response_text

    async def aclose(self) -> None:
        """Close the HTTP client."""
        if self._client:
            await self._client.aclose()
            self._client = None

    async def __aenter__(self) -> "ResponseVerificationService":
        return self

    async def __aexit__(self, exc_type, exc, tb) -> None:
        await self.aclose()


__all__ = ["ResponseVerificationService", "VerificationResult"]
